/*
 * Student API
 * This is an API to query students
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: romuit02@hs-esslingen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * Student
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-28T09:49:16.604301600+01:00[Europe/Berlin]")
public class Student {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_AGE = "age";
  @SerializedName(SERIALIZED_NAME_AGE)
  private Integer age;

  public static final String SERIALIZED_NAME_ENROLMENT_NUMBER = "enrolmentNumber";
  @SerializedName(SERIALIZED_NAME_ENROLMENT_NUMBER)
  private Integer enrolmentNumber;

  public static final String SERIALIZED_NAME_FIELD_OF_STUDY = "fieldOfStudy";
  @SerializedName(SERIALIZED_NAME_FIELD_OF_STUDY)
  private String fieldOfStudy;

  public Student id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", required = true, value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Student name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Lula Haverland", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Student age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @ApiModelProperty(example = "21", required = true, value = "")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public Student enrolmentNumber(Integer enrolmentNumber) {
    this.enrolmentNumber = enrolmentNumber;
    return this;
  }

   /**
   * Get enrolmentNumber
   * @return enrolmentNumber
  **/
  @ApiModelProperty(example = "732597", required = true, value = "")
  public Integer getEnrolmentNumber() {
    return enrolmentNumber;
  }

  public void setEnrolmentNumber(Integer enrolmentNumber) {
    this.enrolmentNumber = enrolmentNumber;
  }

  public Student fieldOfStudy(String fieldOfStudy) {
    this.fieldOfStudy = fieldOfStudy;
    return this;
  }

   /**
   * Get fieldOfStudy
   * @return fieldOfStudy
  **/
  @ApiModelProperty(example = "Software Engineering", required = true, value = "")
  public String getFieldOfStudy() {
    return fieldOfStudy;
  }

  public void setFieldOfStudy(String fieldOfStudy) {
    this.fieldOfStudy = fieldOfStudy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Student student = (Student) o;
    return Objects.equals(this.id, student.id) &&
        Objects.equals(this.name, student.name) &&
        Objects.equals(this.age, student.age) &&
        Objects.equals(this.enrolmentNumber, student.enrolmentNumber) &&
        Objects.equals(this.fieldOfStudy, student.fieldOfStudy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, age, enrolmentNumber, fieldOfStudy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Student {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    enrolmentNumber: ").append(toIndentedString(enrolmentNumber)).append("\n");
    sb.append("    fieldOfStudy: ").append(toIndentedString(fieldOfStudy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

