openapi: 3.0.0
info:
  description: This is an API to query students
  version: "1.0.0"
  title: Student API
  contact:
    email: romuit02@hs-esslingen.de
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
paths:

  /students:
    get:
      summary: Lists all students currently enrolled
      operationId: listStudents
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student'
        '500':
          description: Internal Server error
    post:
      summary: Adds a new student to the system
      operationId: addStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/student'
      responses:
        '201':
          description: Ressource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/student'
        '409':
          description: An existing item already exists

  /student/{id}:
    get:
      summary: returns student information by id
      operationId: getStudentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Search result matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Updates a student in the system
      operationId: updateStudent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Item updated
        '400':
          description: Invalid input, object invalid
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/student'
        description: Student item to update

    patch:
      summary: Partial update of student information
      operationId: partialUpdateStudent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Item updated
        '400':
          description: 'invalid input, object invalid'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/student'
        description: Student item to update

    delete:
      summary: Deletion of a student in the system
      operationId: studentDeletion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Student deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
servers:
  - url: 'http://localhost:8080/v1'
components:
  schemas:
    student:
      type: object
      required:
        - name
        - age
        - enrolmentNumber
        - fieldOfStudy
      properties:
        uuid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: Lula Haverland
        age:
          type: integer
          format: int32
          example: 21
        enrolmentNumber:
          type: integer
          format: int32
          example: 732597
        fieldOfStudy:
          type: string
          example: Software Engineering
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string